apiVersion: browserconfig.selenosis.io/v1
kind: BrowserConfig
metadata:
  name: browserconfig-playwright-mcp-example
  namespace: selenosis
spec:
  template:
    labels:
      app: browser

    resources:
      requests:
        cpu: "1"
        memory: "1Gi"
      limits:
        cpu: "2"
        memory: "2Gi"

    imagePullPolicy: Always

    volumes:
    - emptyDir:
        medium: Memory
      name: dshm

    volumeMounts:
    - mountPath: /dev/shm
      name: dshm

    sidecars:
    - name: seleniferous
      image: "alcounit/seleniferous:v2.0.8"
      imagePullPolicy: Always
      env:
      - name: SESSION_CREATE_TIMEOUT
        value: "10m"
      - name: SESSION_IDLE_TIMEOUT
        value: "10m"
      - name: BROWSER_PORT
        value: "8808"
      - name: POD_IP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
      resources:
        limits:
          cpu: "0.2"
          memory: "128Mi"
        requests:
          cpu: "0.1"
          memory: "64Mi"

    env:
    - name: DEBUG
      value: "pw:*"

  browsers:
    playwright-mcp:
      "0.0.75":
        image: mcr.microsoft.com/playwright/mcp:v0.0.75
        args:
        - "--port"
        - "8808"
        - "--host"
        - "0.0.0.0"
        - "--no-sandbox"
        - "--timeout-navigation"
        - "120000"
